import { describe, it, expect } from 'vitest'
import { getPublisherPreferences } from '~/server/utils/publisherPreferences'

// getPublisherPreferences is the pure merge: registry defaults overlaid with the
// publisher's stored map, whitelisted to known keys and boolean values. Eligibility
// (approved, non-ghost) is enforced by callers before persisting — not here.
describe('getPublisherPreferences', () => {
  it('returns registry defaults (OFF) for absent/empty input', () => {
    expect(getPublisherPreferences(undefined)).toEqual({ autoGenerateDraftsByCrawler: false })
    expect(getPublisherPreferences(null)).toEqual({ autoGenerateDraftsByCrawler: false })
    expect(getPublisherPreferences({})).toEqual({ autoGenerateDraftsByCrawler: false })
    expect(getPublisherPreferences({ preferences: null })).toEqual({ autoGenerateDraftsByCrawler: false })
    expect(getPublisherPreferences({ preferences: {} })).toEqual({ autoGenerateDraftsByCrawler: false })
  })

  it('overlays a stored boolean over the default', () => {
    expect(getPublisherPreferences({ preferences: { autoGenerateDraftsByCrawler: true } }))
      .toEqual({ autoGenerateDraftsByCrawler: true })
    expect(getPublisherPreferences({ preferences: { autoGenerateDraftsByCrawler: false } }))
      .toEqual({ autoGenerateDraftsByCrawler: false })
  })

  it('ignores unknown stored keys (can never inject extra keys)', () => {
    const result = getPublisherPreferences({ preferences: { autoGenerateDraftsByCrawler: true, somethingElse: true } as never })
    expect(result).toEqual({ autoGenerateDraftsByCrawler: true })
    expect(Object.keys(result)).toEqual(['autoGenerateDraftsByCrawler'])
  })

  it('ignores non-boolean stored values, falling back to the default', () => {
    expect(getPublisherPreferences({ preferences: { autoGenerateDraftsByCrawler: 'yes' as never } }))
      .toEqual({ autoGenerateDraftsByCrawler: false })
    expect(getPublisherPreferences({ preferences: { autoGenerateDraftsByCrawler: 1 as never } }))
      .toEqual({ autoGenerateDraftsByCrawler: false })
  })
})
