import { ObjectId } from 'mongodb'
import { requirePublisherAuth } from '~/server/utils/requirePublisherAuth'
import { getMongoConnection } from '~/server/utils/mongodb'

/** Admin: publishers currently opted in to crawler auto-drafts. Manager-only. */
export default defineEventHandler(async (event) => {
  await requirePublisherAuth(event, { requirePlatformStaff: true })

  const config = useRuntimeConfig() as Record<string, string>
  const { db } = await getMongoConnection()
  const publishers = db.collection(config.mongodbCollectionPublishers || 'publishers')
  const accountsCol = db.collection(config.mongodbCollectionAccounts || 'accounts')

  const docs = await publishers
    .find(
      { 'preferences.autoGenerateDraftsByCrawler': true },
      { projection: { waId: 1, fullName: 1, accountId: 1, accountName: 1, status: 1 } },
    )
    .toArray()

  // Resolve account titles (account name relocated to accounts.title).
  const accountIds = [...new Set(docs.map((d) => d.accountId).filter(Boolean) as string[])]
  const accountDocs = accountIds.length
    ? await accountsCol.find({ _id: { $in: accountIds.map((id) => new ObjectId(id)) } }, { projection: { title: 1 } }).toArray()
    : []
  const titleById = new Map(accountDocs.map((a) => [a._id.toString(), a.title || '']))

  return docs.map((d) => ({
    id: d._id.toString(),
    waId: d.waId,
    fullName: d.fullName || '',
    // Keep the `publishingAs` key for the UI; source it from the account title.
    publishingAs: d.accountId ? (titleById.get(d.accountId) || '') : (d.accountName || ''),
    status: d.status,
  }))
})
