import { requirePublisherAuth } from '~/server/utils/requirePublisherAuth'
import { getMongoConnection } from '~/server/utils/mongodb'

/** Admin: publishers currently opted in to crawler auto-drafts. Manager-only. */
export default defineEventHandler(async (event) => {
  await requirePublisherAuth(event, { requireManager: true })

  const config = useRuntimeConfig() as Record<string, string>
  const { db } = await getMongoConnection()
  const publishers = db.collection(config.mongodbCollectionPublishers || 'publishers')

  const docs = await publishers
    .find(
      { 'preferences.autoGenerateDraftsByCrawler': true },
      { projection: { waId: 1, fullName: 1, publishingAs: 1, status: 1 } },
    )
    .toArray()

  return docs.map((d) => ({
    id: d._id.toString(),
    waId: d.waId,
    fullName: d.fullName || '',
    publishingAs: d.publishingAs || '',
    status: d.status,
  }))
})
