import { getMongoConnection } from '~/server/utils/mongodb'
import { requireApiSecret } from '~/server/utils/requireApiSecret'
import { ensureAccountForPublisher, resolveAccountTitle } from '~/server/utils/accountScope'
import { notifyLog } from '~/server/utils/notifyLog'

export default defineEventHandler(async (event) => {
  requireApiSecret(event)
  const body = await readBody<{ waId: string }>(event)
  const waId = typeof body?.waId === 'string' ? body.waId.trim() : ''

  if (!waId) {
    throw createError({
      statusCode: 400,
      statusMessage: 'Bad Request',
      message: 'waId is required',
    })
  }

  const config = useRuntimeConfig()
  const mongoUri = config.mongodbUri || process.env.MONGODB_URI
  const mongoDbName = config.mongodbDbName || process.env.MONGODB_DB_NAME
  const collectionName =
    config.mongodbCollectionPublishers ||
    process.env.MONGODB_COLLECTION_PUBLISHERS ||
    'publishers'

  if (!mongoUri || !mongoDbName) {
    throw createError({
      statusCode: 503,
      statusMessage: 'Service Unavailable',
    })
  }

  try {
    const { db } = await getMongoConnection()
    const collection = db.collection(collectionName)
    const now = new Date()

    // Capture prior status first so the log notice fires once (pending → approved), never on
    // a re-approve of an already-approved publisher.
    const before = await collection.findOne({ waId })
    if (!before) {
      throw createError({
        statusCode: 404,
        statusMessage: 'Not Found',
        message: 'Publisher not found',
      })
    }
    const isFirstApproval = before.status !== 'approved'
    const setFields: Record<string, unknown> = { status: 'approved', updatedAt: now, approvedAt: now }
    // On their FIRST approval, opt new publishers into crawler auto-draft generation by default.
    // Only on first approval so a later admin opt-out (crawler page) survives a re-approve.
    if (isFirstApproval) setFields['preferences.autoGenerateDraftsByCrawler'] = true
    await collection.updateOne({ waId }, { $set: setFields })

    // Every approved publisher belongs to an account (auto-created, idempotent).
    const pubDoc = await collection.findOne({ waId })
    if (pubDoc) await ensureAccountForPublisher(pubDoc as Parameters<typeof ensureAccountForPublisher>[0])

    // On a genuine first approval, post a notice to the log group (account title resolved
    // after the account exists). Best-effort — notifyLog never throws.
    if (isFirstApproval && pubDoc) {
      const accountTitle = await resolveAccountTitle({ accountId: pubDoc.accountId, accountName: pubDoc.accountName, waId })
      const msg = [
        'מפרסם חדש אושר✅',
        `שם מלא: *${pubDoc.fullName || '-'}*`,
        `מטעם: *${accountTitle || '-'}*`,
        `סוג אירועים: *${pubDoc.eventTypesDescription || '-'}*`,
        `מזהה וואטסאפ: *${waId || '-'}*`,
        `אימייל: *${pubDoc.email || '-'}*`,
      ].join('\n')
      await notifyLog(msg)
    }

    return { success: true }
  } catch (err: unknown) {
    if (err && typeof err === 'object' && 'statusCode' in err) throw err
    console.error('[PublishersAPI] Approve error:', err instanceof Error ? err.message : String(err))
    throw createError({
      statusCode: 500,
      statusMessage: 'Internal Server Error',
    })
  }
})
