import { getMongoConnection } from '~/server/utils/mongodb'
import { requireApiSecret } from '~/server/utils/requireApiSecret'
import { ensureAccountForPublisher, resolveAccountTitle } from '~/server/utils/accountScope'
import { notifyLog } from '~/server/utils/notifyLog'
import { resolveActorName } from '~/server/utils/approvers'

/**
 * Approve a publisher. ATOMIC first-wins: only a still-`pending` publisher transitions to approved,
 * so concurrent approvers can't double-process. Records who approved (actor) and returns a structured
 * result so the wa-bot can either run the side effects (winner) or tell a late approver it was
 * already handled (loser).
 *
 * Body: { waId, actorWaId? }. Response: { applied, publisherName, actorName } on win, or
 * { applied:false, resolvedStatus, by, publisherName } when someone already acted.
 */
export default defineEventHandler(async (event) => {
  requireApiSecret(event)
  const body = await readBody<{ waId?: string; actorWaId?: string }>(event)
  const waId = typeof body?.waId === 'string' ? body.waId.trim() : ''
  const actorWaId = typeof body?.actorWaId === 'string' ? body.actorWaId.trim() : ''

  if (!waId) {
    throw createError({ statusCode: 400, statusMessage: 'Bad Request', message: 'waId is required' })
  }

  const config = useRuntimeConfig()
  const mongoUri = config.mongodbUri || process.env.MONGODB_URI
  const mongoDbName = config.mongodbDbName || process.env.MONGODB_DB_NAME
  const collectionName =
    config.mongodbCollectionPublishers || process.env.MONGODB_COLLECTION_PUBLISHERS || 'publishers'
  if (!mongoUri || !mongoDbName) {
    throw createError({ statusCode: 503, statusMessage: 'Service Unavailable' })
  }

  try {
    const { db } = await getMongoConnection()
    const collection = db.collection(collectionName)
    const now = new Date()
    const actorName = actorWaId ? await resolveActorName(actorWaId) : 'מאשר'

    // Atomic first-wins claim: pending → approved. Returns the doc only to the winner.
    const pubDoc = await collection.findOneAndUpdate(
      { waId, status: 'pending' },
      {
        $set: {
          status: 'approved',
          updatedAt: now,
          approvedAt: now,
          approvedByWaId: actorWaId || null,
          approvedByName: actorName,
          // First approval also opts the publisher into crawler auto-draft generation.
          'preferences.autoGenerateDraftsByCrawler': true,
        },
      },
      { returnDocument: 'after' },
    )

    if (pubDoc) {
      // Winner: ensure the account/owner membership exists, then post the one-time log notice.
      await ensureAccountForPublisher(pubDoc as Parameters<typeof ensureAccountForPublisher>[0])
      const accountTitle = await resolveAccountTitle({ accountId: pubDoc.accountId, accountName: pubDoc.accountName, waId })
      const msg = [
        'מפרסם חדש אושר✅',
        `שם מלא: *${pubDoc.fullName || '-'}*`,
        `מטעם: *${accountTitle || '-'}*`,
        `סוג אירועים: *${pubDoc.eventTypesDescription || '-'}*`,
        `מזהה וואטסאפ: *${waId || '-'}*`,
        `אימייל: *${pubDoc.email || '-'}*`,
        `אושר על ידי: *${actorName}*`,
      ].join('\n')
      await notifyLog(msg)
      return { applied: true, publisherName: pubDoc.fullName || '', actorName }
    }

    // Loser: someone already acted (or the publisher is gone). Report the resolved state + who.
    const current = await collection.findOne(
      { waId },
      { projection: { status: 1, fullName: 1, approvedByName: 1, rejectedByName: 1 } },
    )
    if (!current) return { applied: false, resolvedStatus: 'gone', by: null, publisherName: '' }
    const resolvedStatus =
      current.status === 'approved' ? 'approved'
        : current.status === 'rejected' || current.status === 'ghost' ? 'rejected'
          : String(current.status || 'unknown')
    const by = resolvedStatus === 'approved' ? (current.approvedByName || null)
      : resolvedStatus === 'rejected' ? (current.rejectedByName || null) : null
    return { applied: false, resolvedStatus, by, publisherName: current.fullName || '' }
  } catch (err: unknown) {
    if (err && typeof err === 'object' && 'statusCode' in err) throw err
    console.error('[PublishersAPI] Approve error:', err instanceof Error ? err.message : String(err))
    throw createError({ statusCode: 500, statusMessage: 'Internal Server Error' })
  }
})
