import { ObjectId } from 'mongodb'
import type { Db } from 'mongodb'
import type { H3Event } from 'h3'
import { softDeleteEventStatsData } from '~/server/utils/eventStats.service'
import { logAuthEvent } from '~/server/utils/authLog'
import { ensureAccountForPublisher, resolveAccountTitle } from '~/server/utils/accountScope'
import { notifyLog } from '~/server/utils/notifyLog'

/**
 * Shared publisher approve/reject core — the ATOMIC first-wins claim + side effects, used by BOTH the
 * wa-bot endpoints (API-secret) and the admin portal endpoints (session). The caller resolves the
 * actor's display name (approver name for the bot; the staffer's name for the portal). Behavior mirrors
 * the original publishers/{approve,reject}.post.ts exactly.
 */
export interface ActorInfo { actorWaId?: string | null; actorName: string }
export type ApprovalResult =
  | { applied: true; publisherName: string; actorName: string }
  | { applied: false; resolvedStatus: string; by: string | null; publisherName: string }

function eventsCollection(db: Db, config: Record<string, string>) {
  return db.collection(config.mongodbCollectionEventsWaBot || config.mongodbCollectionEvents || 'events')
}

/** Report the resolved state to a "loser" (someone already approved/rejected, or the publisher is gone). */
async function loserResult(db: Db, config: Record<string, string>, waId: string): Promise<ApprovalResult> {
  const collection = db.collection(config.mongodbCollectionPublishers || 'publishers')
  const current = await collection.findOne({ waId }, { projection: { status: 1, fullName: 1, approvedByName: 1, rejectedByName: 1 } })
  if (!current) return { applied: false, resolvedStatus: 'gone', by: null, publisherName: '' }
  const resolvedStatus =
    current.status === 'approved' ? 'approved'
      : current.status === 'rejected' || current.status === 'ghost' ? 'rejected'
        : String(current.status || 'unknown')
  const by = resolvedStatus === 'approved' ? (current.approvedByName || null)
    : resolvedStatus === 'rejected' ? (current.rejectedByName || null) : null
  return { applied: false, resolvedStatus, by, publisherName: current.fullName || '' }
}

/** Approve a pending publisher (atomic). Winner: create account+owner membership, opt into crawler, notify owner. */
export async function approvePublisher(db: Db, config: Record<string, string>, waId: string, actor: ActorInfo): Promise<ApprovalResult> {
  const collection = db.collection(config.mongodbCollectionPublishers || 'publishers')
  const now = new Date()

  const pubDoc = await collection.findOneAndUpdate(
    { waId, status: 'pending' },
    {
      $set: {
        status: 'approved',
        updatedAt: now,
        approvedAt: now,
        approvedByWaId: actor.actorWaId || null,
        approvedByName: actor.actorName,
        'preferences.autoGenerateDraftsByCrawler': true,
      },
    },
    { returnDocument: 'after' },
  )

  if (!pubDoc) return loserResult(db, config, waId)

  await ensureAccountForPublisher(pubDoc as Parameters<typeof ensureAccountForPublisher>[0])
  const accountTitle = await resolveAccountTitle({ accountId: pubDoc.accountId, accountName: pubDoc.accountName, waId })
  const msg = [
    'מפרסם חדש אושר✅',
    `שם מלא: *${pubDoc.fullName || '-'}*`,
    `מטעם: *${accountTitle || '-'}*`,
    `סוג אירועים: *${pubDoc.eventTypesDescription || '-'}*`,
    `מזהה וואטסאפ: *${waId || '-'}*`,
    `אימייל: *${pubDoc.email || '-'}*`,
    `אושר על ידי: *${actor.actorName}*`,
  ].join('\n')
  await notifyLog(msg)
  return { applied: true, publisherName: pubDoc.fullName || '', actorName: actor.actorName }
}

/** Reject a pending publisher (atomic). Winner: soft-delete their events+stats, then ghost (on-behalf) or hard-delete. */
export async function rejectPublisher(db: Db, config: Record<string, string>, waId: string, actor: ActorInfo, event?: H3Event): Promise<ApprovalResult> {
  const collection = db.collection(config.mongodbCollectionPublishers || 'publishers')
  const now = new Date()

  const doc = await collection.findOneAndUpdate(
    { waId, status: 'pending' },
    { $set: { status: 'rejected', rejectedAt: now, updatedAt: now, rejectedByWaId: actor.actorWaId || null, rejectedByName: actor.actorName } },
    { returnDocument: 'after' },
  )

  if (!doc) return loserResult(db, config, waId)

  // Cascade soft-delete the publisher's events + stats.
  const eventsCol = eventsCollection(db, config)
  const publisherId = doc._id.toString()
  const deletedAt = now
  const theirEvents = await eventsCol
    .find({ $or: [{ 'event.publisherId': publisherId }, { 'rawEvent.publisher.waId': waId }], deletedAt: { $exists: false } }, { projection: { _id: 1 } })
    .toArray()
  for (const ev of theirEvents) {
    await eventsCol.updateOne({ _id: ev._id }, { $set: { deletedAt, isActive: false } })
    await softDeleteEventStatsData(ev._id.toString(), deletedAt)
  }

  if (doc.createdOnBehalf) {
    await collection.updateOne({ waId }, { $set: { status: 'ghost', updatedAt: now } })
  } else {
    await collection.deleteOne({ waId })
    const membershipsCol = db.collection(config.mongodbCollectionMemberships || 'memberships')
    await membershipsCol.deleteMany({ publisherId })
    if (doc.accountId) {
      const remaining = await collection.countDocuments({ accountId: doc.accountId })
      if (remaining === 0) {
        try {
          const accountsCol = db.collection(config.mongodbCollectionAccounts || 'accounts')
          await accountsCol.updateOne({ _id: new ObjectId(String(doc.accountId)) }, { $set: { deletedAt: now, isActive: false } })
        } catch (e) {
          console.warn('[publisherApproval] Reject: could not release account', doc.accountId, e instanceof Error ? e.message : e)
        }
      }
    }
  }

  if (event) await logAuthEvent(event, 'publisher_rejected', waId, { cascadedEvents: theirEvents.length })
  return { applied: true, publisherName: doc.fullName || '', actorName: actor.actorName }
}
