/**
 * Publisher-level preference registry.
 *
 * Single source of truth for per-publisher toggles stored on the `publishers`
 * collection in a `preferences` object. Distinct from account-level features
 * ([features.const.js]) — those are entitlements shared by all publishers in an
 * account; these are settings for one publisher.
 *
 * Resolved server-side by getPublisherPreferences() (server/utils/publisherPreferences.ts)
 * and surfaced to the client via /api/auth/me. Only approved (non-ghost) publishers
 * are eligible. `default` is used when a publisher has no explicit value.
 */
export const PUBLISHER_PREFERENCES = [
  { key: 'autoGenerateDraftsByCrawler', label: 'יצירת טיוטות אוטומטית מקבוצות וואטסאפ', default: false },
]

export const PREFERENCE_KEYS = PUBLISHER_PREFERENCES.map((p) => p.key)

export const PREFERENCE_DEFAULTS = Object.fromEntries(PUBLISHER_PREFERENCES.map((p) => [p.key, p.default]))
